[app]
ns = "OpenRufusWebInfra"
stage = "Dev"

[api]
uri = "API_URL" # e.g. example.com

[cloudfront]
secretHeaderName = "x-cloudfront-secret"
secretHeaderValue = "YOUR_SECRET_VALUE"

[repository]
path = "haandol/open-rufus"
branch = "main"
