[app]
ns = "OpenRufusWebInfra"
stage = "Dev"

[alb]
arn = "YOUR_ALB_ARN"

[cloudfront]
secretHeaderName = "x-cloudfront-secret"
secretHeaderValue = "YOUR_SECRET_VALUE"

[repository]
path = "haandol/open-rufus"
branch = "main"
