[app]
ns = "OpenRufus"
stage = "Dev"

# [vpc]
# vpcId = "vpc-xyz"

[auth]
apiKey = "YOUR_API_KEY"                                                  # generate random 32 length api key
callbackUrls = ["http://localhost:8000/auth/oauth/aws-cognito/callback"]

[cert]
recordName = "YOUR_PREFIX"                        # e.g. myapi
domainName = "YOUR_DOMAIN_NAME"                   # e.g. example.com
hostedZoneId = "YOUR_ROUTE53_HOSTED_ZONE_ID"
certificateArn = "YOUR_CERTIFICATION_MANAGER_ARN"

[chatbot]
tableName = "chatbot"
modelName = "us.anthropic.claude-3-5-haiku-20241022-v1:0"

[cloudfront]
secretHeaderName = "x-cloudfront-secret-key"
secretHeaderValue = "YOUR_SECRET_HEADER_VALUE" # same as web-infra

[external]
apiKey = "YOUR_API_KEY"

[external.itemSearch]
indexName = "item-search"

[external.itemRecommend]
indexName = "item-recommend"
